apiVersion: v1
kind: Service
metadata:
  name: "{{ services }}"
  namespace: "{{ k8s_namespace }}"
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: {{ node_port }}
    port: {{ CoreIssuePort }}
    protocol: TCP
    targetPort: {{ CoreIssuePort }}
  selector:
    app: "{{ deployment }}"
  sessionAffinity: None
  type: NodePort