apiVersion: v1
kind: Service
metadata:
  name: services-appserver
  namespace: "{{ k8s_namespace }}"
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: {{ node_port | int }}
    port: 4422
    protocol: TCP
    targetPort: 4422
  selector:
    app: dbbappserver-services
  sessionAffinity: None
  type: NodePort
---
