apiVersion: v1
kind: Service
metadata:
  name: coreissue-appserver
  namespace: "{{ k8s_namespace }}"
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31421
    port: 4421
    protocol: TCP
    targetPort: 4421
  selector:
    app: dbbappserver-coreissue
  sessionAffinity: None
  type: NodePort
---
