apiVersion: v1
kind: Service
metadata:
  name: coreapp-appserver
  namespace: "{{ k8s_namespace }}"
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31424
    port: 4424
    protocol: TCP
    targetPort: 4424
  selector:
    app: dbbappserver-coreapp
  sessionAffinity: None
  type: NodePort
---
