apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ deployment }}
  name: {{ deployment }}
  namespace: {{ k8s_namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ deployment }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ deployment }}
    spec:
      containers:
        - args:
            - CoreAuth
            - "1"
          envFrom:
            - configMapRef:
                name: {{ configmap }}
          image: {{ docker_registry }}/{{ image_name }}:{{ image_version }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthy
              port: 7013
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: {{ deployment }}
          ports:
            - containerPort: 4427
              name: coreauth
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthy
              port: 7013
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1200m
              memory: 2000m
            requests:
              cpu: 900m
              memory: 1000m
          securityContext:
            windowsOptions:
              gmsaCredentialSpecName: "{{ gmsa_account }}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: C:\\tracefiles
              name: trace-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regsecret
      nodeSelector:
        kubernetes.io/os: windows
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: D:\\tracefiles
            type: ""
          name: trace-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - qa
      tolerations:
        - key: qa
          operator: Exists
          effect: NoSchedule