apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rundbb-tranapicall
  name: rundbb-tranapicall
  namespace: {{ k8s_namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rundbb-tranapicall
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rundbb-tranapicall
    spec:
      containers:
        - args:
            - coreissue
            - "40"
          envFrom:
            - configMapRef:
                name: configmap-coreissue
          image: {{ docker_registry }}/{{ image_name }}:{{ image_version }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthy
              port: 7049
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: rundbb-tranapicall
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthy
              port: 7049
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 950m
              memory: 4048Mi
            requests:
              cpu: 850m
              memory: 3536Mi
          securityContext:
            windowsOptions:
              gmsaCredentialSpecName: "{{ gmsa_account }}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: C:\\tracefiles
              name: trace-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regsecret
      nodeSelector:
        kubernetes.io/os: windows
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: C:\\tracefiles
            type: ""
          name: trace-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - qa
      tolerations:
        - key: qa
          operator: Exists
          effect: NoSchedule
